[package]
name = "burri"
version = "0.1.0"
edition = "2021"
license = "WTFPL"
publish = false

[dependencies]
clap = { version = "3", features = ["cargo"] }
rand = "0.8.5"
solana-clap-v3-utils = "=1.11.5"
solana-cli-config = "=1.11.5"
solana-client = "=1.11.5"
solana-logger = "=1.11.5"
solana-remote-wallet = "=1.11.5"
solana-sdk = "=1.11.5"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
solana-validator = "=1.11.5"

[workspace]
